name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
        eslint-version: [8, 9]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install --frozen-lockfile

      - name: Use ESLint ${{ matrix.eslint-version }}
        run: bun add --dev eslint@${{ matrix.eslint-version }}

      - name: Test
        run: bun run test
